#!/bin/sh

if [ -z "$1" ]; then
	echo "Provide the file to replace the variables in as the first argument"
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "$1 does not exist"
	exit 2
fi

envsubst '${DHIS_FWD_PORT} ${OPENEMPI_FWD_PORT} ${IL_CONSOLE_CERT} ${IL_CONSOLE_KEY} ${IL_TRUSTCHAIN} ${SERVER_NAME} ${OPENSHR_FWD_PORT}' < "$1" > "$1.tmp"
mv "$1.tmp" "$1"
